{{- if .Values.openshiftHaproxyLogsCollector.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}
  labels:
    {{- include "lagoon-logging.openshiftHaproxyLogsCollector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openshiftHaproxyLogsCollector.replicaCount }}
  serviceName: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}
  selector:
    matchLabels:
      {{- include "lagoon-logging.openshiftHaproxyLogsCollector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/env-configmap: {{ include (print $.Template.BasePath "/openshift-haproxy-logs-collector.env.configmap.yaml") . | sha256sum }}
        checksum/fluent-conf-configmap: {{ include (print $.Template.BasePath "/openshift-haproxy-logs-collector.fluent-conf.configmap.yaml") . | sha256sum }}
    {{- with .Values.openshiftHaproxyLogsCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lagoon-logging.openshiftHaproxyLogsCollector.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.openshiftHaproxyLogsCollector.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-fluentd
        securityContext:
          {{- toYaml .Values.openshiftHaproxyLogsCollector.securityContext | nindent 10 }}
        image: "{{ .Values.openshiftHaproxyLogsCollector.image.repository }}:{{ .Values.openshiftHaproxyLogsCollector.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.openshiftHaproxyLogsCollector.image.pullPolicy }}
        ports:
        - containerPort: 24231
          protocol: TCP
          name: metrics
        - containerPort: 5141
          protocol: UDP
          name: haproxy-logs
        readinessProbe:
          tcpSocket:
            port: 24231
          initialDelaySeconds: 20
        livenessProbe:
          tcpSocket:
            port: 24231
          initialDelaySeconds: 120
        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-fluent-conf
          subPath: fluent.conf
        envFrom:
        - configMapRef:
            name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-env
        resources:
          {{- toYaml .Values.openshiftHaproxyLogsCollector.resources | nindent 10 }}
      {{- with .Values.openshiftHaproxyLogsCollector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openshiftHaproxyLogsCollector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openshiftHaproxyLogsCollector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: fluent.conf
            path: fluent.conf
          name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-fluent-conf
        name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-fluent-conf
{{- end }}
