{{- if .Values.openshiftHaproxyLogsCollector.enabled }}
{{- if .Values.openshiftHaproxyLogsCollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.serviceAccountName" . }}
  labels:
    {{- include "lagoon-logging.openshiftHaproxyLogsCollector.labels" . | nindent 4 }}
  {{- with .Values.openshiftHaproxyLogsCollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
