{{- if .Values.openshiftHaproxyLogsCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lagoon-logging.openshiftHaproxyLogsCollector.fullname" . }}-fluent-conf
  labels:
    {{- include "lagoon-logging.openshiftHaproxyLogsCollector.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        storage.path  /buffers


    [INPUT]
        Name                syslog
        Mode                udp
        Port                5141
        Buffer_Chunk_Size   32000
        Buffer_Max_Size     65507
        Parser              haproxy

    [PARSER]
        Name   haproxy
        Format regex
        Regex  ^.{,15} (?<process_name>\w+)\[(?<pid>\d+)\]: (?<client_ip>\S+):(?<client_port>\d+) \[(?<request_date>\S+)\] (?<frontend_name>\S+) (?<backend_type>\S+):(?<docker_container_id>(?<kubernetes_namespace_name>\S+):\S+\/pod:(?<kubernetes_pod_name>[^:]+):(?<kubernetes_container_name>[^:]+)):\S+ (?<TR>[\d-]+)\/(?<Tw>[\d-]+)\/(?<Tc>[\d-]+)\/(?<Tr>[\d-]+)\/(?<Ta>[\d+-]+) (?<status_code>\d+) (?<bytes_read>[\d+]+) (?<captured_request_cookie>\S+) (?<captured_response_cookie>\S+) (?<termination_state>\S+) (?<actconn>\d+)\/(?<feconn>\d+)\/(?<beconn>\d+)\/(?<srv_conn>\d+)\/(?<retries>\d+) (?<srv_queue>\d+)\/(?<backend_queue>\d+) (\{(?<request_host>.+)\|(?<request_user_agent>.+)?\} )?"(?<http_request>.+)"
        Time_Key request_date
        Time_Format %d/%b/%Y:%T.%L
        Types pid:integer client_port:integer TR:integer Tw:integer Tc:integer Tr:integer Ta:integer bytes_read:integer actconn:integer feconn:integer beconn:integer srv_conn:integer retries:integer srv_queue:integer backend_queue:integer
      </parse>

    [OUTPUT]
        Name          stdout
        Match         *
        Format        json
        json_date_key false
{{- end }}
